---
title: "ARIMA Prediction Of Stock 999999"
author: "Wu Wei"
date: "2017-1-4"
output: html_document
---

## Synopsis


## Pure Arima Modelling
### Library input & Data Input
```{r}
rm(list = ls())
suppressMessages(library(forecast))

setwd("d://MyR//stock//")
original.data <- read.csv("goldmonthly.csv")
# (original.data)

close.price <- as.ts(original.data[,5])
# volume <- as.ts(original.data[,6])
kdj.k <- as.ts(original.data[,7])
kdj.d <- as.ts(original.data[,8])


```

```{r, fig.height=9, fig.width=10}
BoxCox.lambda(kdj.d)
BoxCox.lambda(kdj.k)
BoxCox.lambda(close.price)
```

```{r, fig.height=9, fig.width=10}
DrawKDJPlot <- function(arg.kdj.k, arg.kdj.d, 
                             arg.training.set.endpoint, arg.forecast.period){
        

        training.set.kdj.k <- window(arg.kdj.k, start = 1, end = arg.training.set.endpoint)
        test.set.kdj.k <- window(arg.kdj.k, start = arg.training.set.endpoint + 1,
                                       end = arg.training.set.endpoint + arg.forecast.period)
        
        training.set.kdj.d <- window(arg.kdj.d, start = 1, end = arg.training.set.endpoint)
        test.set.kdj.d <- window(arg.kdj.d, start = arg.training.set.endpoint + 1,
                                       end = arg.training.set.endpoint + arg.forecast.period)        


        par(mfrow = c(2,1))


        fit.arima.kdj.k <- auto.arima(training.set.kdj.k)
        fit.arima.kdj.d <- auto.arima(training.set.kdj.d)
        
        estimated.kdj.k <- forecast(fit.arima.kdj.k, h = length(test.set.kdj.k))
        estimated.kdj.d <- forecast(fit.arima.kdj.d, h = length(test.set.kdj.d))        

        plot(estimated.kdj.k, type = "o")
        lines(test.set.kdj.k, col = "red", type = "o")
        
        plot(estimated.kdj.d, type = "o")
        lines(test.set.kdj.d, col = "red", type = "o")
        
}


```

```{r, fig.height=9, fig.width=10}
DrawKDJPlot(kdj.k, kdj.d, arg.training.set.endpoint = 203, arg.forecast.period = 3)

```

        



```{r, fig.height=9, fig.width=10}
CompareAccuracy <- function(arg.object, 
                            arg.forecast.period,
                            arg.training.set.endpoint, 
                            arg.comparison.period,
                            arg.flag,
                            arg.pdq.df,
                            arg.stepwise,
                            arg.maxorder,
                            arg.xreg,
                            arg.lambda.flag){
        
        training.set.object.1 <- window(arg.object, start = 1, 
                                             end = arg.training.set.endpoint)
        
        test.set.object.1 <- window(arg.object, start = arg.training.set.endpoint + 1,
                                         end = arg.training.set.endpoint + arg.forecast.period)
        
        # browser()
        xreg.object.1 <- arg.xreg[1:arg.training.set.endpoint,]
        xreg.object.test.1 <- arg.xreg[(arg.training.set.endpoint + 1):
                                               (arg.training.set.endpoint + arg.forecast.period),]
        
        if(arg.flag == 0){
        
                if(arg.stepwise == FALSE){

                        if(is.null(xreg.object.1)){
                                if(arg.lambda.flag == FALSE){
                                        fit.arima.object.1 <- auto.arima(training.set.object.1)                                                  
                                }else{
                                        
                                        fit.arima.object.1 <- auto.arima(training.set.object.1,
                                                                         lambda = BoxCox.lambda(training.set.object.1))
                                }

                        }else{
                                if(arg.lambda.flag == FALSE){
                                        fit.arima.object.1 <- auto.arima(training.set.object.1, xreg = xreg.object.1)                                                                     
                                }else{
                                        fit.arima.object.1 <- auto.arima(training.set.object.1, 
                                                                         xreg = xreg.object.1,
                                                                         lambda = BoxCox.lambda(training.set.object.1))                             
                                }
     
                        }

                }else{
 
                        if(is.null(xreg.object.1)){
                                if(arg.lambda.flag == FALSE){
                                        fit.arima.object.1 <- auto.arima(training.set.object.1,
                                                                         max.order = arg.maxorder,
                                                                         stepwise = FALSE,
                                                                         approximation = FALSE)                                        
                                }else{
                                        fit.arima.object.1 <- auto.arima(training.set.object.1,
                                                                         max.order = arg.maxorder,
                                                                         stepwise = FALSE,
                                                                         approximation = FALSE,
                                                                         lambda = BoxCox.lambda(training.set.object.1))
                                }

                        }else{
                                if(arg.lambda.flag == FALSE){
                                        fit.arima.object.1 <- auto.arima(training.set.object.1,
                                                                         max.order = arg.maxorder,
                                                                         stepwise = FALSE,
                                                                         approximation = FALSE, xreg = xreg.object.1)                
                                }else{
                                        fit.arima.object.1 <- auto.arima(training.set.object.1,
                                                                         max.order = arg.maxorder,
                                                                         stepwise = FALSE,
                                                                         approximation = FALSE, xreg = xreg.object.1,
                                                                         lambda = BoxCox.lambda(training.set.object.1))                
                                }
                                
                        }
                        
                }
 
        }else{

                if(arg.pdq.df$newdrift[1] == 1){
                        if(is.null(xreg.object.1)){
                                if(arg.lambda.flag == FALSE){
                                        fit.arima.object.1 <- Arima(training.set.object.1, order = c(arg.pdq.df$newp[1],
                                                                                                     arg.pdq.df$newd[1],
                                                                                                     arg.pdq.df$newq[1]),
                                                                    include.drift = TRUE)                                  
                                }else{
                                        fit.arima.object.1 <- Arima(training.set.object.1, order = c(arg.pdq.df$newp[1],
                                                                                             arg.pdq.df$newd[1],
                                                                                             arg.pdq.df$newq[1]),
                                                            include.drift = TRUE,
                                                            lambda = BoxCox.lambda(training.set.object.1))                          
                                }
                                
                        }else{
                                if(arg.lambda.flag == FALSE){
                                        fit.arima.object.1 <- Arima(training.set.object.1, order = c(arg.pdq.df$newp[1],
                                                                                                     arg.pdq.df$newd[1],
                                                                                                     arg.pdq.df$newq[1]),
                                                                    include.drift = TRUE, xreg = xreg.object.1)                                                                        
                                }else{
                                        fit.arima.object.1 <- Arima(training.set.object.1, order = c(arg.pdq.df$newp[1],
                                                                                                     arg.pdq.df$newd[1],
                                                                                                     arg.pdq.df$newq[1]),
                                                                    include.drift = TRUE, xreg = xreg.object.1,
                                                                    lambda = BoxCox.lambda(training.set.object.1))                                
                                }

                        }
                        
                        
                }else{
                        if(is.null(xreg.object.1)){
                                if(arg.lambda.flag == FALSE){
                                        fit.arima.object.1 <- Arima(training.set.object.1, order = c(arg.pdq.df$newp[1],
                                                                                                     arg.pdq.df$newd[1],
                                                                                                     arg.pdq.df$newq[1]))                                                        
                                }else{
                                        fit.arima.object.1 <- Arima(training.set.object.1, order = c(arg.pdq.df$newp[1],
                                                                                                     arg.pdq.df$newd[1],
                                                                                                     arg.pdq.df$newq[1]),
                                                                    lambda = BoxCox.lambda(training.set.object.1))                
                                }

                                
                        }else{
                                if(arg.lambda.flag == FALSE){
                                        fit.arima.object.1 <- Arima(training.set.object.1, order = c(arg.pdq.df$newp[1],
                                                                                                     arg.pdq.df$newd[1],
                                                                                                     arg.pdq.df$newq[1]), 
                                                                    xreg = xreg.object.1)                                        
                                }else{
                                        fit.arima.object.1 <- Arima(training.set.object.1, order = c(arg.pdq.df$newp[1],
                                                                                                     arg.pdq.df$newd[1],
                                                                                                     arg.pdq.df$newq[1]), 
                                                                    xreg = xreg.object.1,
                                                                    lambda = BoxCox.lambda(training.set.object.1))                
                                }
                
                        }
                        
                }
                
        }
        
        if(is.null(xreg.object.test.1)){
        
                fc.arima.object.1 <- forecast(fit.arima.object.1, h = length(test.set.object.1))        
        }else{
                fc.arima.object.1 <- forecast(fit.arima.object.1, h = length(test.set.object.1), 
                                           xreg = xreg.object.test.1)        
        }
        
        
        df.accuracy <- accuracy(fc.arima.object.1, test.set.object.1)
        pvalue <- Box.test(residuals(fit.arima.object.1), lag=10, 
                           fitdf=sum(fit.arima.object.1$arma[c(1,2)]))$p.value
        
        if("drift" %in% names(fit.arima.object.1$coef)){

                result <- t(array(c(arg.training.set.endpoint, 
                                    fit.arima.object.1$arma[c(1,6,2)],
                                    df.accuracy[2,],
                                    1,
                                    pvalue,
                                    BoxCox.lambda(training.set.object.1)), 
                                  dim = c(15,1)))                                
        }else{

                result <- t(array(c(arg.training.set.endpoint, 
                                    fit.arima.object.1$arma[c(1,6,2)],
                                    df.accuracy[2,],
                                    0,
                                    pvalue,
                                    BoxCox.lambda(training.set.object.1)), 
                                  dim = c(15,1)))                
        }

        
        col.names.accuracy <- colnames(df.accuracy)
        

        for(i in 1:arg.comparison.period){

                end.point2 <- arg.training.set.endpoint + i
                training.set.object.2 <- window(arg.object, start = 1, end = end.point2)
                test.set.object.2 <- window(arg.object, start = end.point2 + 1,
                                                 end = end.point2 + arg.forecast.period)

                xreg.object.2 <- arg.xreg[1:end.point2,]
                xreg.object.test.2 <- arg.xreg[(end.point2 + 1):
                                                       (end.point2 + arg.forecast.period),]
                
                if(arg.flag == 0){

                        if(arg.stepwise == FALSE){

                                if(is.null(xreg.object.2)){
                                        if(arg.lambda.flag == FALSE){
                                                fit.arima.object.2 <- auto.arima(training.set.object.2)                                                     
                                        }else{
                                                fit.arima.object.2 <- auto.arima(training.set.object.2,
                                                                                 lambda = BoxCox.lambda(training.set.object.2))     
                                        }

                                }else{
                                        if(arg.lambda.flag == FALSE){
                                                fit.arima.object.2 <- auto.arima(training.set.object.2, xreg = xreg.object.2)                   
                                        }else{
                                                fit.arima.object.2 <- auto.arima(training.set.object.2, xreg = xreg.object.2,
                                                                                 lambda = BoxCox.lambda(training.set.object.2))           
                                        }
                                                                          
                                }
                                
                        }else{
        
                                if(is.null(xreg.object.2)){
                                        if(arg.lambda.flag == FALSE){
                                                fit.arima.object.2 <- auto.arima(training.set.object.2,
                                                                                 max.order = arg.maxorder,
                                                                                 stepwise = FALSE,
                                                                                 approximation = FALSE)
                                        }else{
                                                fit.arima.object.2 <- auto.arima(training.set.object.2,
                                                                                 max.order = arg.maxorder,
                                                                                 stepwise = FALSE,
                                                                                 approximation = FALSE,
                                                                                 lambda = BoxCox.lambda(training.set.object.2))
                                        }
                                }else{
                                        if(arg.lambda.flag == FALSE){
                                                fit.arima.object.2 <- auto.arima(training.set.object.2,
                                                                                 max.order = arg.maxorder,
                                                                                 stepwise = FALSE,
                                                                                 approximation = FALSE, xreg = xreg.object.2)                                                      }else{
                                                  fit.arima.object.2 <- auto.arima(training.set.object.2,
                                                                                   max.order = arg.maxorder,
                                                                                   stepwise = FALSE,
                                                                                   approximation = FALSE, xreg = xreg.object.2,
                                                                                   lambda = BoxCox.lambda(training.set.object.2))                                                  }
                                }

                        }
        
                }else{
                        if(arg.pdq.df$newdrift[1 + i] == 1){
                                if(is.null(xreg.object.2)){
                                        if(arg.lambda.flag == FALSE){
                                                fit.arima.object.2 <- Arima(training.set.object.2, order = c(arg.pdq.df$newp[1 + i],
                                                                                                             arg.pdq.df$newd[1 + i],
                                                                                                             arg.pdq.df$newq[1 + i]),
                                                                            include.drift = TRUE)
                                        }else{
                                                fit.arima.object.2 <- Arima(training.set.object.2, order = c(arg.pdq.df$newp[1 + i],
                                                                                                             arg.pdq.df$newd[1 + i],
                                                                                                             arg.pdq.df$newq[1 + i]),
                                                                            include.drift = TRUE,
                                                                            lambda = BoxCox.lambda(training.set.object.2))
                                        }
                                }else{
                                        if(arg.lambda.flag == FALSE){
                                                fit.arima.object.2 <- Arima(training.set.object.2, order = c(arg.pdq.df$newp[1 + i],
                                                                                                             arg.pdq.df$newd[1 + i],
                                                                                                             arg.pdq.df$newq[1 + i]),
                                                                            include.drift = TRUE, xreg = xreg.object.2)                                                                }else{
                                                fit.arima.object.2 <- Arima(training.set.object.2, order = c(arg.pdq.df$newp[1 + i],
                                                                                                             arg.pdq.df$newd[1 + i],
                                                                                                             arg.pdq.df$newq[1 + i]),
                                                                            include.drift = TRUE, xreg = xreg.object.2,
                                                                            lambda = BoxCox.lambda(training.set.object.2))
                                           } 
                                }
                                
                        }else{
                        
                                if(is.null(xreg.object.2)){

                                        if(arg.lambda.flag == FALSE){
                                                fit.arima.object.2 <- Arima(training.set.object.2, order = c(arg.pdq.df$newp[1 + i],
                                                                                                             arg.pdq.df$newd[1 + i],
                                                                                                             arg.pdq.df$newq[1 + i]))                                                            
                                        }else{
                                                fit.arima.object.2 <- Arima(training.set.object.2, order = c(arg.pdq.df$newp[1 + i],
                                                                                                             arg.pdq.df$newd[1 + i],
                                                                                                             arg.pdq.df$newq[1 + i]),
                                                                            lambda = BoxCox.lambda(training.set.object.2))            
                                        }
                                         
                                }else{
                                        if(arg.lambda.flag == FALSE){
                                                fit.arima.object.2 <- Arima(training.set.object.2, order = c(arg.pdq.df$newp[1 + i],
                                                                                                             arg.pdq.df$newd[1 + i],
                                                                                                             arg.pdq.df$newq[1 + i]),
                                                                            xreg = xreg.object.2)                                                                                                
                                        }else{
                                                fit.arima.object.2 <- Arima(training.set.object.2, order = c(arg.pdq.df$newp[1 + i],
                                                                                                             arg.pdq.df$newd[1 + i],
                                                                                                             arg.pdq.df$newq[1 + i]),
                                                                            xreg = xreg.object.2,
                                                                            lambda = BoxCox.lambda(training.set.object.2))                                                
                                        }

                                }
                                

                        }
                        
                }

                # fc.arima.object.2 <- forecast(fit.arima.object.2, h = length(test.set.object.2),
                #                                    xreg = xreg.object.test.2)

                if(is.null(xreg.object.test.2)){
                        
                        fc.arima.object.2 <- forecast(fit.arima.object.2, h = length(test.set.object.2))        
                }else{
                        fc.arima.object.2 <- forecast(fit.arima.object.2, h = length(test.set.object.2), 
                                                      xreg = xreg.object.test.2)        
                }
                
                pvalue <- Box.test(residuals(fit.arima.object.2), lag=10, 
                           fitdf=sum(fit.arima.object.2$arma[c(1,2)]))$p.value
                
                if("drift" %in% names(fit.arima.object.2$coef)){

                        result2 <- t(array(c(arg.training.set.endpoint + i,
                                            fit.arima.object.2$arma[c(1,6,2)],
                                            accuracy(fc.arima.object.2, test.set.object.2)[2,],
                                            1,
                                            pvalue,
                                            BoxCox.lambda(training.set.object.2)),
                                          dim = c(15,1)))
                }else{

                        result2 <- t(array(c(arg.training.set.endpoint + i,
                                            fit.arima.object.2$arma[c(1,6,2)],
                                            accuracy(fc.arima.object.2, test.set.object.2)[2,],
                                            0,
                                            pvalue,
                                            BoxCox.lambda(training.set.object.2)),
                                          dim = c(15,1)))
                }

                result <- rbind(result, result2)

        }

        df.result <- data.frame(result)
        colnames(df.result) <- c("seq", "p","d","q", col.names.accuracy, "drift", "pvalue","lambda")
        # View(df.result)
        
        if(arg.flag == 0){
                return(df.result)        
        }else{
                return(cbind(arg.pdq.df, df.result[,-(1:4)]))
        }
                        
}


```


```{r}
training.set.endpoint <- 300

comparison.period <- 100

result <- CompareAccuracy(kdj.d, 
                          arg.forecast.period = 4,
                          arg.training.set.endpoint = training.set.endpoint, 
                          arg.comparison.period = comparison.period,
                          arg.flag = 0,
                          arg.pdq.df = NULL,
                          arg.stepwise = FALSE,
                          arg.maxorder = 5)

# result[,c(14:17)] <- result[,c(2:4,13)]
# 
# colnames(result)[c(14:17)] <- c("newp","newd","newq","newdrift")

# result <- result[,c(1:4,13,5:12,14:17)]

result.stepwise <- CompareAccuracy(kdj.d, 
                          arg.forecast.period = 4,
                          arg.training.set.endpoint = training.set.endpoint, 
                          arg.comparison.period = comparison.period,
                          arg.flag = 0,
                          arg.pdq.df = NULL,
                          arg.stepwise = TRUE,
                          arg.maxorder = 5)

result.stepwise.maxorder <- CompareAccuracy(kdj.d, 
                          arg.forecast.period = 4,
                          arg.training.set.endpoint = training.set.endpoint, 
                          arg.comparison.period = comparison.period,
                          arg.flag = 0,
                          arg.pdq.df = NULL,
                          arg.stepwise = TRUE,
                          arg.maxorder = 9)

summarized.result <- cbind(result, result.stepwise, result.stepwise.maxorder)[,c(1:4, 13, 6, 14:18,27,20,28:32, 41, 34, 42)]

(summarized.result[order(summarized.result$RMSE.2 - summarized.result$RMSE.1),])


mean(summarized.result$RMSE)
mean(summarized.result$RMSE.1)
mean(summarized.result$RMSE.2)

result[result$p != result.stepwise$p | result$d != result.stepwise$d | result$q != result.stepwise$q, "seq"]

```



```{r}

# result$newp[1:23] <- 2
# result$newq[1:23] <- 1

# result$newd[5:12] <- 2
# result$newq <- 0
#  
# result$newp[13:14] <- 0
# result$newd[13:14] <- 1
# result$newq[13:14] <- 1
# result$newdrift[13:14] <- 0
# 
# result$newp[31:47] <- 0
# result$newd[31:47] <- 1
# result$newq[31:47] <- 1

```

```{r}

second.result <- CompareAccuracy(kdj.d, 
                          arg.forecast.period = 4,
                          arg.training.set.endpoint = 240, 
                          arg.comparison.period = 20,
                          arg.flag = 1,
                          arg.pdq.df = result)

(second.result[,c(1:4, 7, 14:16, 19)])

mean(second.result[,7])
mean(second.result[,19])
```


```{r, fig.height=9, fig.width=10}
DrawPlot <- function(arg.object, arg.training.set.endpoint, 
                             arg.forecast.period, arg.pdq.df){
        

        training.set.object <- window(arg.object, start = 1, end = arg.training.set.endpoint)
        test.set.object <- window(arg.object, start = arg.training.set.endpoint + 1,
                                       end = arg.training.set.endpoint + arg.forecast.period)        

        fit.arima.object <- auto.arima(training.set.object)
        
        fc.object <- forecast(fit.arima.object, h = arg.forecast.period)        

        rownum <- as.integer(row.names(arg.pdq.df[arg.pdq.df$seq == arg.training.set.endpoint,]))
        
        # browser()
        if(arg.pdq.df$newdrift[rownum] == 1){
                
                fit.arima.object.manual <- Arima(training.set.object, order = c(arg.pdq.df$newp[rownum],
                                                                                            arg.pdq.df$newd[rownum],
                                                                                            arg.pdq.df$newq[rownum]),
                                                      include.drift = TRUE)
        }else{
                
                fit.arima.object.manual <- Arima(training.set.object, order = c(arg.pdq.df$newp[rownum],
                                                                                            arg.pdq.df$newd[rownum],
                                                                                            arg.pdq.df$newq[rownum]))
        }
        
                
        fc.object.manual <- forecast(fit.arima.object.manual, h = arg.forecast.period)        
        
        par(mfrow = c(2,1))
        plot(fc.object, type = "o", 
             xlim = c(arg.training.set.endpoint - 80, arg.training.set.endpoint + arg.forecast.period))
        lines(test.set.object, col = "red", type = "o")
        
        plot(fc.object.manual, type = "o",
             xlim = c(arg.training.set.endpoint - 80, arg.training.set.endpoint + arg.forecast.period))
        lines(test.set.object, col = "red", type = "o")
}


```

```{r, fig.height=9, fig.width=10}
DrawPlot(kdj.d, arg.forecast.period = 4, second.result, arg.training.set.endpoint = 219)
```

```{r}
result.kdj.k <- CompareAccuracy(kdj.k, 
                          arg.forecast.period = 4,
                          arg.training.set.endpoint = 210, 
                          arg.comparison.period = 75,
                          arg.flag = 0,
                          arg.pdq.df = NULL)

result.kdj.k[,c(14:17)] <- result.kdj.k[,c(2:4,13)]

colnames(result.kdj.k)[c(14:17)] <- c("newp","newd","newq","newdrift")

result.kdj.k <- result.kdj.k[,c(1:4,13,5:12,14:17)]
```

```{r}

# result.kdj.k$newp[3:10] <- 3
# result.kdj.k$newp[9:13] <- 1
# 
# # result$newd[5:12] <- 2
# result.kdj.k$newq[9:13] <- 0
#  
# result$newp[13:14] <- 0
# result$newd[13:14] <- 1
# result$newq[13:14] <- 1
# result$newdrift[13:14] <- 0
# 
# result$newp[31:47] <- 0
# result$newd[31:47] <- 1
# result$newq[31:47] <- 1

```

```{r}

second.result.kdj.k <- CompareAccuracy(kdj.k, 
                          arg.forecast.period = 4,
                          arg.training.set.endpoint = 210, 
                          arg.comparison.period = 75,
                          arg.flag = 1,
                          arg.pdq.df = result.kdj.k)

(second.result.kdj.k[,c(1:4, 7, 14:16, 19)])

mean(second.result.kdj.k[,7])
mean(second.result.kdj.k[,19])
```

```{r, fig.height=9, fig.width=10}
DrawPlot(kdj.k, 
         arg.forecast.period = 4, 
         second.result.kdj.k, 
         arg.training.set.endpoint = 210)
```

```{r}
result <- CompareAccuracy(kdj.d, 
                          arg.forecast.period = 4,
                          arg.training.set.endpoint = 200, 
                          arg.comparison.period = 10,
                          arg.flag = 0,
                          arg.pdq.df = NULL)

result.kdj.k <- CompareAccuracy(kdj.k, 
                          arg.forecast.period = 4,
                          arg.training.set.endpoint = 200, 
                          arg.comparison.period = 10,
                          arg.flag = 0,
                          arg.pdq.df = NULL)

compare.result <- cbind(result, result.kdj.k)[,c(1:4, 6, 13:17,19, 26)]

mean(compare.result[,5])
mean(compare.result[,11])
```

```{r}
getwd()
load("D:\\MyR\\stock\\result.RData")

rm(list = ls())
load("D:\\MyR\\stock\\result300400.RData")
save(result, result.stepwise,result.stepwise.maxorder, file = "result300400.RData")
```

