---
title: "ARIMA Prediction Of Stock 999999"
author: "Wu Wei"
date: "2017-1-4"
output: html_document
---

## Synopsis


## Pure Arima Modelling
### Library input & Data Input
```{r}

suppressMessages(library(forecast))
```

```{r, fig.height=8, fig.width=10}
rm(list = ls())

setwd("d://MyR//stock//")
original.data <- read.csv("goldweekly.csv")
# (original.data)

close.price <- ts(window(original.data[,5], start = 1500, end = 1900), start = 1)
# volume <- as.ts(original.data[,6])
# kdj.k <- as.ts(original.data[,7])
kdj.d <- ts(window(original.data[,8], start = 1500, end = 1900), start = 1)


```



```{r}

reg.lagged.df <- cbind(kdj.d,       
                ts(c(NA, kdj.d[-length(kdj.d)])),
                ts(c(NA, NA, head(kdj.d, length(kdj.d) - 2))),
                ts(c(NA, NA, NA, head(kdj.d, length(kdj.d) - 3))))
```

```{r, fig.height=9, fig.width=10}
CompareObjectAccuracy <- function(arg.object, 
                            arg.forecast.period,
                            arg.training.set.endpoint, 
                            arg.comparison.period,
                            arg.maxorder){

        training.set.object.1 <- window(arg.object, start = 1, 
                                             end = arg.training.set.endpoint)
        
        test.set.object.1 <- window(arg.object, start = arg.training.set.endpoint + 1,
                                         end = arg.training.set.endpoint + arg.forecast.period)
        

        # browser()
        fit.arima.object.1 <- auto.arima(training.set.object.1,
                                         max.order = arg.maxorder,
                                         stepwise = FALSE,
                                         approximation = FALSE)                
        
        
        fc.arima.object.1 <- forecast(fit.arima.object.1, h = length(test.set.object.1))        
        
        
        df.accuracy <- accuracy(fc.arima.object.1, test.set.object.1)
        pvalue <- Box.test(residuals(fit.arima.object.1), lag=10, 
                           fitdf=sum(fit.arima.object.1$arma[c(1,2)]))$p.value
        
        
        result <- t(array(c(arg.training.set.endpoint,
                            fit.arima.object.1$arma[c(1,6,2)],
                            df.accuracy[2,],
                            ("drift" %in% names(fit.arima.object.1$coef)) * 1,
                            pvalue),
                          dim = c(14,1)))
        
                # if("drift" %in% names(fit.arima.object.1$coef)){
        # 
        #         result <- t(array(c(arg.training.set.endpoint, 
        #                             fit.arima.object.1$arma[c(1,6,2)],
        #                             df.accuracy[2,],
        #                             1,
        #                             pvalue), 
        #                           dim = c(14,1)))                                
        # }else{
        # 
        #         result <- t(array(c(arg.training.set.endpoint, 
        #                             fit.arima.object.1$arma[c(1,6,2)],
        #                             df.accuracy[2,],
        #                             0,
        #                             pvalue), 
        #                           dim = c(14,1)))                
        # }

        
        col.names.accuracy <- colnames(df.accuracy)
        

        for(i in 1:arg.comparison.period){

                end.point2 <- arg.training.set.endpoint + i
                training.set.object.2 <- window(arg.object, start = 1, end = end.point2)
                test.set.object.2 <- window(arg.object, start = end.point2 + 1,
                                                 end = end.point2 + arg.forecast.period)

                fit.arima.object.2 <- auto.arima(training.set.object.2,
                                                 max.order = arg.maxorder,
                                                 stepwise = FALSE,
                                                 approximation = FALSE)                          
                
                fc.arima.object.2 <- forecast(fit.arima.object.2, h = length(test.set.object.2))        
                
                pvalue <- Box.test(residuals(fit.arima.object.2), lag=10, 
                           fitdf=sum(fit.arima.object.2$arma[c(1,2)]))$p.value
                
                
                result2 <- t(array(c(arg.training.set.endpoint + i,
                                            fit.arima.object.2$arma[c(1,6,2)],
                                            accuracy(fc.arima.object.2, test.set.object.2)[2,],
                                            ("drift" %in% names(fit.arima.object.2$coef)) * 1,
                                            pvalue),
                                          dim = c(14,1)))
                                
                # if("drift" %in% names(fit.arima.object.2$coef)){
                # 
                #         result2 <- t(array(c(arg.training.set.endpoint + i,
                #                             fit.arima.object.2$arma[c(1,6,2)],
                #                             accuracy(fc.arima.object.2, test.set.object.2)[2,],
                #                             1,
                #                             pvalue),
                #                           dim = c(14,1)))
                # }else{
                # 
                #         result2 <- t(array(c(arg.training.set.endpoint + i,
                #                             fit.arima.object.2$arma[c(1,6,2)],
                #                             accuracy(fc.arima.object.2, test.set.object.2)[2,],
                #                             0,
                #                             pvalue),
                #                           dim = c(14,1)))
                # }

                result <- rbind(result, result2)

        }

        df.result <- data.frame(result)
        colnames(df.result) <- c("seq", "p","d","q", col.names.accuracy, "drift", "pvalue")

        return(df.result)        

}


```



```{r, fig.height=9, fig.width=10}
CompareObjectXregAccuracy <- function(arg.object, 
                            arg.forecast.period,
                            arg.training.set.endpoint, 
                            arg.comparison.period,
                            arg.maxorder,
                            arg.xreg){
        
        training.set.object.1 <- window(arg.object, start = 1, 
                                             end = arg.training.set.endpoint)
        
        test.set.object.1 <- window(arg.object, start = arg.training.set.endpoint + 1,
                                         end = arg.training.set.endpoint + arg.forecast.period)
        
        xreg.object.1 <- arg.xreg[1:arg.training.set.endpoint,]

        xreg.object.test.1 <- arg.xreg[(arg.training.set.endpoint + 1):
                                               (arg.training.set.endpoint + arg.forecast.period),]
        
        fit.arima.object.1 <- auto.arima(training.set.object.1,
                                         max.order = arg.maxorder,
                                         stepwise = FALSE,
                                         approximation = FALSE, 
                                         xreg = xreg.object.1)                
        
        
        fc.arima.object.1 <- forecast(fit.arima.object.1, h = length(test.set.object.1), 
                                      xreg = xreg.object.test.1)        
        
        
        df.accuracy <- accuracy(fc.arima.object.1, test.set.object.1)
        pvalue <- Box.test(residuals(fit.arima.object.1), lag=10, 
                           fitdf=sum(fit.arima.object.1$arma[c(1,2)]))$p.value
        
        if("drift" %in% names(fit.arima.object.1$coef)){

                result <- t(array(c(arg.training.set.endpoint, 
                                    fit.arima.object.1$arma[c(1,6,2)],
                                    df.accuracy[2,],
                                    1,
                                    pvalue), 
                                  dim = c(14,1)))                                
        }else{

                result <- t(array(c(arg.training.set.endpoint, 
                                    fit.arima.object.1$arma[c(1,6,2)],
                                    df.accuracy[2,],
                                    0,
                                    pvalue), 
                                  dim = c(14,1)))                
        }

        
        col.names.accuracy <- colnames(df.accuracy)
        

        for(i in 1:arg.comparison.period){

                end.point2 <- arg.training.set.endpoint + i
                training.set.object.2 <- window(arg.object, start = 1, end = end.point2)
                test.set.object.2 <- window(arg.object, start = end.point2 + 1,
                                                 end = end.point2 + arg.forecast.period)

                xreg.object.2 <- arg.xreg[1:end.point2,]
                xreg.object.test.2 <- arg.xreg[(end.point2 + 1):
                                                       (end.point2 + arg.forecast.period),]

                fit.arima.object.2 <- auto.arima(training.set.object.2,
                                                 max.order = arg.maxorder,
                                                 stepwise = FALSE,
                                                 approximation = FALSE, 
                                                 xreg = xreg.object.2)                          

                fc.arima.object.2 <- forecast(fit.arima.object.2, h = length(test.set.object.2), 
                                              xreg = xreg.object.test.2)        
                
                pvalue <- Box.test(residuals(fit.arima.object.2), lag=10, 
                           fitdf=sum(fit.arima.object.2$arma[c(1,2)]))$p.value
                
                if("drift" %in% names(fit.arima.object.2$coef)){

                        result2 <- t(array(c(arg.training.set.endpoint + i,
                                            fit.arima.object.2$arma[c(1,6,2)],
                                            accuracy(fc.arima.object.2, test.set.object.2)[2,],
                                            1,
                                            pvalue),
                                          dim = c(14,1)))
                }else{

                        result2 <- t(array(c(arg.training.set.endpoint + i,
                                            fit.arima.object.2$arma[c(1,6,2)],
                                            accuracy(fc.arima.object.2, test.set.object.2)[2,],
                                            0,
                                            pvalue),
                                          dim = c(14,1)))
                }

                result <- rbind(result, result2)

        }

        df.result <- data.frame(result)
        colnames(df.result) <- c("seq", "p","d","q", col.names.accuracy, "drift", "pvalue")

        return(df.result)        

}


```

```{r, fig.height=9, fig.width=10}
CompareObjectEstimatedXregAccuracy <- function(arg.object, 
                            arg.forecast.period,
                            arg.training.set.endpoint, 
                            arg.comparison.period,
                            arg.maxorder,
                            arg.reg.variable){
        
        training.set.object.1 <- window(arg.object, start = 1, 
                                             end = arg.training.set.endpoint)
        
        test.set.object.1 <- window(arg.object, start = arg.training.set.endpoint + 1,
                                         end = arg.training.set.endpoint + arg.forecast.period)
        

        fit.xreg.object.1 <- auto.arima(arg.reg.variable[1:arg.training.set.endpoint],
                                        max.order = arg.maxorder,
                                        stepwise = FALSE,
                                        approximation = FALSE)                

        fc.xreg.object.1 <- forecast(fit.xreg.object.1, h = length(test.set.object.1))
        
        xreg.object.est.1 <- c(window(arg.reg.variable, start = 1,end = arg.training.set.endpoint), 
                                      fc.xreg.object.1$mean)
        
        
        xreg.lagged.df.1 <- cbind(xreg.object.est.1,       
                ts(c(NA, xreg.object.est.1[-length(xreg.object.est.1)])),
                ts(c(NA, NA, head(xreg.object.est.1, length(xreg.object.est.1) - 2))),
                ts(c(NA, NA, NA, head(xreg.object.est.1, length(xreg.object.est.1) - 3))))
        
        xreg.object.1 <- xreg.lagged.df.1[1:arg.training.set.endpoint,]

        xreg.object.test.1 <- xreg.lagged.df.1[(arg.training.set.endpoint + 1):
                                               (arg.training.set.endpoint + arg.forecast.period),]
        
        fit.arima.object.1 <- auto.arima(training.set.object.1,
                                         max.order = arg.maxorder,
                                         stepwise = FALSE,
                                         approximation = FALSE, 
                                         xreg = xreg.object.1)                
        
        
        fc.arima.object.1 <- forecast(fit.arima.object.1, h = length(test.set.object.1), 
                                      xreg = xreg.object.test.1)        
        
        
        df.accuracy <- accuracy(fc.arima.object.1, test.set.object.1)
        pvalue <- Box.test(residuals(fit.arima.object.1), lag=10, 
                           fitdf=sum(fit.arima.object.1$arma[c(1,2)]))$p.value
        
        if("drift" %in% names(fit.arima.object.1$coef)){

                result <- t(array(c(arg.training.set.endpoint, 
                                    fit.arima.object.1$arma[c(1,6,2)],
                                    df.accuracy[2,],
                                    1,
                                    pvalue), 
                                  dim = c(14,1)))                                
        }else{

                result <- t(array(c(arg.training.set.endpoint, 
                                    fit.arima.object.1$arma[c(1,6,2)],
                                    df.accuracy[2,],
                                    0,
                                    pvalue), 
                                  dim = c(14,1)))                
        }

        
        col.names.accuracy <- colnames(df.accuracy)
        

        for(i in 1:arg.comparison.period){

                end.point2 <- arg.training.set.endpoint + i
                training.set.object.2 <- window(arg.object, start = 1, end = end.point2)
                test.set.object.2 <- window(arg.object, start = end.point2 + 1,
                                                 end = end.point2 + arg.forecast.period)

                fit.xreg.object.2 <- auto.arima(arg.reg.variable[1:end.point2],
                                                max.order = arg.maxorder,
                                                stepwise = FALSE,
                                                approximation = FALSE)                
                
                fc.xreg.object.2 <- forecast(fit.xreg.object.2, h = length(test.set.object.2))
                
                xreg.object.est.2 <- c(window(arg.reg.variable, start = 1, end = end.point2),
                                           fc.xreg.object.2$mean)

                xreg.lagged.df.2 <- cbind(xreg.object.est.2,       
                                          ts(c(NA, xreg.object.est.2[-length(xreg.object.est.2)])),
                                          ts(c(NA, NA, head(xreg.object.est.2, length(xreg.object.est.2) - 2))),
                                          ts(c(NA, NA, NA, head(xreg.object.est.2, length(xreg.object.est.2) - 3))))
                

                xreg.object.2 <- xreg.lagged.df.2[1:end.point2,]
                xreg.object.test.2 <- xreg.lagged.df.2[(end.point2 + 1):
                                                       (end.point2 + arg.forecast.period),]
                
                # browser()

                fit.arima.object.2 <- auto.arima(training.set.object.2,
                                                 max.order = arg.maxorder,
                                                 stepwise = FALSE,
                                                 approximation = FALSE, 
                                                 xreg = xreg.object.2)                          
                
                
                
                fc.arima.object.2 <- forecast(fit.arima.object.2, h = length(test.set.object.2), 
                                              xreg = xreg.object.test.2)        
                
                pvalue <- Box.test(residuals(fit.arima.object.2), lag=10, 
                           fitdf=sum(fit.arima.object.2$arma[c(1,2)]))$p.value
                
                if("drift" %in% names(fit.arima.object.2$coef)){

                        result2 <- t(array(c(arg.training.set.endpoint + i,
                                            fit.arima.object.2$arma[c(1,6,2)],
                                            accuracy(fc.arima.object.2, test.set.object.2)[2,],
                                            1,
                                            pvalue),
                                          dim = c(14,1)))
                }else{

                        result2 <- t(array(c(arg.training.set.endpoint + i,
                                            fit.arima.object.2$arma[c(1,6,2)],
                                            accuracy(fc.arima.object.2, test.set.object.2)[2,],
                                            0,
                                            pvalue),
                                          dim = c(14,1)))
                }

                result <- rbind(result, result2)

        }

        df.result <- data.frame(result)
        colnames(df.result) <- c("seq", "p","d","q", col.names.accuracy, "drift", "pvalue")

        return(df.result)        

}


```



```{r}
training.set.endpoint <- 330

comparison.period <- 10

maxorder <- 9

system.time(result <- CompareObjectAccuracy(arg.object = close.price, 
                            arg.forecast.period = 5,
                            arg.training.set.endpoint = training.set.endpoint, 
                            arg.comparison.period = comparison.period,
                            arg.maxorder = maxorder))

system.time(result.xreg <- CompareObjectXregAccuracy(arg.object = close.price, 
                            arg.forecast.period = 5,
                            arg.training.set.endpoint = training.set.endpoint, 
                            arg.comparison.period = comparison.period,
                            arg.maxorder = maxorder,
                            arg.xreg = reg.lagged.df))

system.time(result.xreg.est <- CompareObjectEstimatedXregAccuracy(arg.object = close.price,
                            arg.forecast.period = 5,
                            arg.training.set.endpoint = training.set.endpoint, 
                            arg.comparison.period = comparison.period,
                            arg.maxorder = maxorder,
                            arg.reg.variable = kdj.d))

final.result <- cbind(result, result.xreg, result.xreg.est)

final.result[,c(1:4, 13, 6, 14:18, 20, 27, 28:32, 34, 41, 42)]

mean(final.result[,6])
mean(final.result[,20])
mean(final.result[,34])

mean(final.result[,6] > final.result[,34]) 

```


        




