---
title: "ARIMA Prediction Of Stock 999999"
author: "Wu Wei"
date: "2017-1-4"
output: html_document
---

## Synopsis


## Pure Arima Modelling
### Library input & Data Input
```{r}
rm(list = ls())

suppressMessages(library(forecast))
suppressMessages(library(parallel))
suppressMessages(library(doParallel))
# suppressMessages(library(sandwich))
# suppressMessages(library(lmtest))

setwd("d://MyR//stock//")
# original.data <- read.csv("goldweekly.csv")

original.data <- read.csv("goldmonthly.csv")
# (original.data)

close.price <- as.ts(original.data[,5])
# volume <- as.ts(original.data[,6])
kdj.k <- as.ts(original.data[,7])
kdj.d <- as.ts(original.data[,8])

# training.set.close.price <- window(close.price, start = 1, end = 240)
# test.set.close.price <- window(close.price, start = 241)
# 
# # training.set.volume <- window(volume, start = 1, end = 240)
# # test.set.volume <- window(volume, start = 241)
# 
# training.set.kdj.k <- window(kdj.k, start = 1, end = 240)
# test.set.kdj.k <- window(kdj.k, start = 241)
# 
# training.set.kdj.d <- window(kdj.d, start = 1, end = 240)
# test.set.kdj.d <- window(kdj.d, start = 241)

```

```{r, fig.height=8, fig.width=10}
cluster <- makeCluster(detectCores() - 1)
registerDoParallel(cluster)

```



### function of Comparison between actual value and forecast result of true kdj.d and estimated kdj.d
```{r, fig.height=9, fig.width=10}
DrawForecastPlot <- function(arg.close.price, arg.kdj.k, arg.kdj.d, arg.forecast.period, 
                             arg.ylabel.offset,
                             arg.xlim.offset,
                             arg.training.set.endpoint){
        
        training.set.close.price <- window(arg.close.price, start = 1, end = arg.training.set.endpoint)
        test.set.close.price <- window(arg.close.price, start = arg.training.set.endpoint + 1,
                                       end = arg.training.set.endpoint + arg.forecast.period)
        
        training.set.kdj.d <- window(arg.kdj.d, start = 1, end = arg.training.set.endpoint)
        test.set.kdj.d <- window(arg.kdj.d, start = arg.training.set.endpoint + 1,
                                       end = arg.training.set.endpoint + arg.forecast.period)        

        reg.lagged.df <- cbind(training.set.kdj.d,       
                               c(NA, training.set.kdj.d[-length(training.set.kdj.d)]),
                               c(NA, NA, head(training.set.kdj.d, length(training.set.kdj.d) - 2)))
        
        fit.lagged.arima <- auto.arima(training.set.close.price, xreg = reg.lagged.df)
        
        par(mfrow = c(2,2))
        fc.lagged.arima <- forecast(fit.lagged.arima, 
                                    xreg = cbind(test.set.kdj.d,
                                                 c(training.set.kdj.d[length(training.set.kdj.d)], 
                                                   test.set.kdj.d[1:(arg.forecast.period - 1)]),
                                                 c(training.set.kdj.d[length(training.set.kdj.d) - 1],
                                                   training.set.kdj.d[length(training.set.kdj.d)],
                                                   as.ts(test.set.kdj.d[1:(arg.forecast.period - 2)]))),
                                    h = arg.forecast.period, 
                                    level = c(80,95))


        y.upper.limit <- signif(max(c(test.set.close.price,
                                      fc.lagged.arima$upper,
                                      tail(fc.lagged.arima$x, arg.xlim.offset))), digits = 2) + 100
        # 
        y.lower.limit <- signif(min(c(test.set.close.price,
                                      fc.lagged.arima$lower,
                                      tail(fc.lagged.arima$x, arg.xlim.offset))), digits = 2) - 100
        
        plot(window(arg.kdj.d, start = arg.training.set.endpoint - arg.xlim.offset, 
                        end = arg.training.set.endpoint + arg.forecast.period), 
             axes = FALSE,type = "l", ylim = c(5,95))
        
        axis(1, 
             at = seq(arg.training.set.endpoint - arg.xlim.offset, 
                      arg.training.set.endpoint + arg.forecast.period, 5), 
             labels = TRUE)

        axis(2, at = seq(5 ,95, 10), labels = TRUE, las = 1)
              
        abline(v = seq(arg.training.set.endpoint - arg.xlim.offset, 
                       arg.training.set.endpoint + arg.forecast.period, 5), 
               col = "springgreen4", 
               lty = "dashed",
               lwd = par("lwd"))        

        abline(h = seq(5,95, 10), 
               col = "springgreen4", 
               lty = "dashed",
               lwd = par("lwd"))
        
        lines(window(arg.kdj.d, start = arg.training.set.endpoint + 1, 
                      end = arg.training.set.endpoint + arg.forecast.period),
             type = "o", col = "red")
        
        lines(window(arg.kdj.k, start = arg.training.set.endpoint - arg.xlim.offset, 
                     end = arg.training.set.endpoint + arg.forecast.period),
              type = "o", col = "orange")
        
        box()
        
        plot(fc.lagged.arima, xlim = c(arg.training.set.endpoint - arg.xlim.offset, 
                                       arg.training.set.endpoint + arg.forecast.period),
             ylim = c(y.lower.limit, y.upper.limit),
             type = "o", plot.conf = TRUE, shaded = TRUE, pi.col = "purple",
             axes = FALSE, main = "Lagged Regression with Arima errors", xlab = "")
        
        lines(test.set.close.price, type = "o",col = "red") 
              
        axis(1, 
             at = seq(arg.training.set.endpoint - arg.xlim.offset, 
                      arg.training.set.endpoint + arg.forecast.period, 5), 
             labels = TRUE)

        # text(seq(arg.training.set.endpoint - arg.xlim.offset, 
        #          arg.training.set.endpoint + arg.forecast.period, 5), 
        #      par("usr")[3] - 250, 
        #      labels = original.data[seq(arg.training.set.endpoint - arg.xlim.offset, 
        #                                 arg.training.set.endpoint + arg.forecast.period, 5), 1], 
        #      srt = 45, 
        #      pos = 1, 
        #      xpd = TRUE)
                
        axis(2, at = seq(y.lower.limit, y.upper.limit, length.out = 5),
             labels = TRUE, las = 1) 
        
        box()
        
        abline(v = seq(arg.training.set.endpoint - arg.xlim.offset, 
                      arg.training.set.endpoint + arg.forecast.period, 5), 
               col = "springgreen4", 
               lty = "dashed",
               lwd = par("lwd"))
        
        abline(h = seq(y.lower.limit, y.upper.limit, length.out = 5), 
               col = "springgreen4", 
               lty = "dashed",
               lwd = par("lwd"))
        
        fit.arima.kdj.d <- auto.arima(training.set.kdj.d)
        
        estimated.kdj.d <- forecast(fit.arima.kdj.d, h = length(test.set.kdj.d))$mean        

        fc.lagged.arima.estimated <- forecast(fit.lagged.arima, 
                                      xreg = cbind(estimated.kdj.d,
                                                   c(training.set.kdj.d[length(training.set.kdj.d)], 
                                                     estimated.kdj.d[1:(arg.forecast.period - 1)]),
                                                   c(training.set.kdj.d[length(training.set.kdj.d) - 1],
                                                     training.set.kdj.d[length(training.set.kdj.d)],
                                                     estimated.kdj.d[1:(arg.forecast.period - 2)])),
                                      h = arg.forecast.period, 
                                      level = c(80,95))


        plot(ts(c(arg.kdj.d[(arg.training.set.endpoint - arg.xlim.offset) : (arg.training.set.endpoint)], 
               estimated.kdj.d), start = (arg.training.set.endpoint - arg.xlim.offset)), 
               axes = FALSE,type = "l", ylim = c(5,95))
        axis(1, 
             at = seq(arg.training.set.endpoint - arg.xlim.offset, 
                      arg.training.set.endpoint + arg.forecast.period, 5), 
             labels = TRUE)

        axis(2, at = seq(5,95, 10), labels = TRUE, las = 1)

        abline(v = seq(arg.training.set.endpoint - arg.xlim.offset, 
                       arg.training.set.endpoint + arg.forecast.period, 5), 
               col = "springgreen4", 
               lty = "dashed",
               lwd = par("lwd"))                                
        
        abline(h = seq(5,95, 10), 
               col = "springgreen4", 
               lty = "dashed",
               lwd = par("lwd"))       
        
        lines(ts(estimated.kdj.d, start = arg.training.set.endpoint + 1), type = "o", col = "darkblue")
        box()
        
        plot(fc.lagged.arima.estimated, xlim = c(arg.training.set.endpoint - arg.xlim.offset, 
                      arg.training.set.endpoint + arg.forecast.period), 
             ylim = c(y.lower.limit, y.upper.limit),
             type = "o", plot.conf = TRUE, shaded = TRUE, pi.col = "purple",
             axes = FALSE, main = "estimated Lagged Regression with Arima errors", xlab = "")
        
        lines(test.set.close.price, type = "o",col = "red")

        axis(1, 
             at = seq(arg.training.set.endpoint - arg.xlim.offset, 
                      arg.training.set.endpoint + arg.forecast.period, 5), 
             labels = FALSE)
        
        text(seq(arg.training.set.endpoint - arg.xlim.offset, 
                      arg.training.set.endpoint + arg.forecast.period, 5), 
             par("usr")[3] - arg.ylabel.offset, 
             labels = original.data[seq(arg.training.set.endpoint - arg.xlim.offset, 
                      arg.training.set.endpoint + arg.forecast.period, 5), 1], 
             srt = 45, 
             pos = 1, 
             xpd = TRUE)
        
        axis(2, at = seq(y.lower.limit, y.upper.limit, length.out = 5),
             labels = TRUE, las = 1) 
        
        box()
        
        abline(v = seq(arg.training.set.endpoint - arg.xlim.offset, 
                      arg.training.set.endpoint + arg.forecast.period, 5), 
               col = "springgreen4", 
               lty = "dashed",
               lwd = par("lwd"))
        
        abline(h = seq(y.lower.limit, y.upper.limit, length.out = 5), 
               col = "springgreen4", 
               lty = "dashed",
               lwd = par("lwd"))        
}


```


```{r, fig.height=9, fig.width=10}
DrawForecastPlot(close.price, kdj.k, kdj.d, arg.forecast.period = 4, 
                 arg.ylabel.offset = 80,
                 arg.xlim.offset = 100,
                 arg.training.set.endpoint = 350)

```
        

```{r, fig.height=9, fig.width=10}
DrawKDJDForecastPlot <- function(arg.close.price, arg.kdj.k, arg.kdj.d, arg.forecast.period, 
                             arg.ylabel.offset,
                             arg.xlim.offset,
                             arg.maxorder.flag,
                             arg.training.set.endpoint,
                             arg.start){
        

        par(mfrow = c(1,1))

        if(arg.training.set.endpoint > length(arg.kdj.d)){
                return(paste0("the length of kdj.d is ", length(arg.kdj.d)))
                
        }

        if((arg.training.set.endpoint <= length(arg.kdj.d)) && 
           (arg.training.set.endpoint >= length(arg.kdj.d) - arg.forecast.period)){
                close.price.data <- ts(c(arg.close.price, rep(tail(arg.close.price,1),arg.forecast.period)))
                kdj.d.data <- ts(c(arg.kdj.d, rep(tail(arg.kdj.d,1),arg.forecast.period)))
                kdj.k.data <- ts(c(arg.kdj.k, rep(tail(arg.kdj.k,1),arg.forecast.period)))
        }else{
                close.price.data <- arg.close.price
                kdj.d.data <- arg.kdj.d
                kdj.k.data <- arg.kdj.k
        }

        training.set.close.price <- window(close.price.data, start = arg.start, end = arg.training.set.endpoint)
        training.set.kdj.d <- window(kdj.d.data, start = arg.start, end = arg.training.set.endpoint)
        training.set.kdj.k <- window(kdj.k.data, start = arg.start, end = arg.training.set.endpoint)
        
        test.set.close.price <- window(close.price.data, start = arg.training.set.endpoint + 1,
                                       end = arg.training.set.endpoint + arg.forecast.period)

        test.set.kdj.d <- window(kdj.d.data, start = arg.training.set.endpoint + 1,
                                 end = arg.training.set.endpoint + arg.forecast.period)                      
        
        test.set.kdj.k <- window(kdj.k.data, start = arg.training.set.endpoint + 1,
                                 end = arg.training.set.endpoint + arg.forecast.period)                      
        
        reg.lagged.df <- cbind(training.set.kdj.d,
                               c(NA, training.set.kdj.d[-length(training.set.kdj.d)]),
                               c(NA, NA, head(training.set.kdj.d, length(training.set.kdj.d) - 2)))
        
        fit.lagged.arima <- auto.arima(training.set.close.price, xreg = reg.lagged.df)
        # 
        if(arg.maxorder.flag  == TRUE){
                par(mfrow = c(2,3))
        }else{
                par(mfrow = c(2,2))
        }
        # 
        fc.lagged.arima <- forecast(fit.lagged.arima,
                                    xreg = cbind(test.set.kdj.d,
                                                 c(training.set.kdj.d[length(training.set.kdj.d)],
                                                   test.set.kdj.d[1:(arg.forecast.period - 1)]),
                                                 c(training.set.kdj.d[length(training.set.kdj.d) - 1],
                                                   training.set.kdj.d[length(training.set.kdj.d)],
                                                   as.ts(test.set.kdj.d[1:(arg.forecast.period - 2)]))),
                                    h = arg.forecast.period,
                                    level = c(80,95))


        y.upper.limit <- signif(max(c(test.set.close.price,
                                      fc.lagged.arima$upper,
                                      tail(fc.lagged.arima$x, arg.xlim.offset))), digits = 2) + 100
        #
        y.lower.limit <- signif(min(c(test.set.close.price,
                                      fc.lagged.arima$lower,
                                      tail(fc.lagged.arima$x, arg.xlim.offset))), digits = 2) - 100

        
        ######        
        plot(window(kdj.d.data, start = arg.training.set.endpoint - arg.xlim.offset,
                        end = arg.training.set.endpoint + arg.forecast.period),
             axes = FALSE,type = "l", ylim = c(5,95))

        axis(1,
             at = seq(arg.training.set.endpoint - arg.xlim.offset,
                      arg.training.set.endpoint + arg.forecast.period, 5),
             labels = TRUE)

        axis(2, at = seq(5 ,95, 10), labels = TRUE, las = 1)

        abline(v = seq(arg.training.set.endpoint - arg.xlim.offset,
                       arg.training.set.endpoint + arg.forecast.period, 5),
               col = "springgreen4",
               lty = "dashed",
               lwd = par("lwd"))

        abline(h = seq(5,95, 10),
               col = "springgreen4",
               lty = "dashed",
               lwd = par("lwd"))

        lines(window(kdj.d.data, start = arg.training.set.endpoint + 1,
                      end = arg.training.set.endpoint + arg.forecast.period),
             type = "o", col = "red")

        lines(window(kdj.k.data, start = arg.training.set.endpoint - arg.xlim.offset,
                     end = arg.training.set.endpoint + arg.forecast.period),
              type = "o", col = "orange")

        box()


        # plot(1,type = "n")
        
        ##########
        
        plot(fc.lagged.arima, xlim = c(arg.training.set.endpoint - arg.xlim.offset,
                                       arg.training.set.endpoint + arg.forecast.period),
             ylim = c(y.lower.limit, y.upper.limit),
             type = "o", plot.conf = TRUE, shaded = TRUE, pi.col = "purple",
             axes = FALSE, main = "Lagged Regression with Arima errors", xlab = "")

        lines(test.set.close.price, type = "o",col = "red")

        axis(1,
             at = seq(arg.training.set.endpoint - arg.xlim.offset,
                      arg.training.set.endpoint + arg.forecast.period, 5),
             labels = TRUE)


        axis(2, at = seq(y.lower.limit, y.upper.limit, length.out = 5),
             labels = TRUE, las = 1)

        box()

        abline(v = seq(arg.training.set.endpoint - arg.xlim.offset,
                      arg.training.set.endpoint + arg.forecast.period, 5),
               col = "springgreen4",
               lty = "dashed",
               lwd = par("lwd"))

        abline(h = seq(y.lower.limit, y.upper.limit, length.out = 5),
               col = "springgreen4",
               lty = "dashed",
               lwd = par("lwd"))
        # 
        if(arg.maxorder.flag  == TRUE){

                plot(1,type = "n", main = "the 3rd")
        }


        fit.arima.kdj.d <- auto.arima(training.set.kdj.d)

        estimated.kdj.d <- forecast(fit.arima.kdj.d, h = length(test.set.kdj.d))$mean

        # fc.lagged.arima.estimated <- forecast(fit.lagged.arima,
        #                               xreg = cbind(estimated.kdj.d,
        #                                            c(training.set.kdj.d[length(training.set.kdj.d)],
        #                                              estimated.kdj.d[1:(arg.forecast.period - 1)]),
        #                                            c(training.set.kdj.d[length(training.set.kdj.d) - 1],
        #                                              training.set.kdj.d[length(training.set.kdj.d)],
        #                                              estimated.kdj.d[1:(arg.forecast.period - 2)])),
        #                               h = arg.forecast.period,
        #                               level = c(80,95))

        ##########   
        plot(ts(c(arg.kdj.d[(arg.training.set.endpoint - arg.xlim.offset) : (arg.training.set.endpoint)],
               estimated.kdj.d), start = (arg.training.set.endpoint - arg.xlim.offset)),
               axes = FALSE,type = "l", ylim = c(5,95))
        axis(1,
             at = seq(arg.training.set.endpoint - arg.xlim.offset,
                      arg.training.set.endpoint + arg.forecast.period, 5),
             labels = TRUE)

        axis(2, at = seq(5,95, 10), labels = TRUE, las = 1)

        abline(v = seq(arg.training.set.endpoint - arg.xlim.offset,
                       arg.training.set.endpoint + arg.forecast.period, 5),
               col = "springgreen4",
               lty = "dashed",
               lwd = par("lwd"))

        abline(h = seq(5,95, 10),
               col = "springgreen4",
               lty = "dashed",
               lwd = par("lwd"))

        lines(ts(estimated.kdj.d, start = arg.training.set.endpoint + 1), type = "o", col = "darkblue")
        box()

        ############ 
        
        
        fit.arima.kdj.d.stepwise <- auto.arima(training.set.kdj.d,
                                               stepwise = FALSE,
                                               approximation = FALSE)

        estimated.kdj.d.stepwise <- forecast(fit.arima.kdj.d.stepwise, h = length(test.set.kdj.d))$mean

        fit.arima.kdj.k.stepwise <- auto.arima(training.set.kdj.k,
                                               stepwise = FALSE,
                                               approximation = FALSE)
        
        estimated.kdj.k.stepwise <- forecast(fit.arima.kdj.k.stepwise, h = length(test.set.kdj.k))$mean
        
        plot(ts(c(arg.kdj.d[(arg.training.set.endpoint - arg.xlim.offset) : (arg.training.set.endpoint)],
                  estimated.kdj.d.stepwise), start = (arg.training.set.endpoint - arg.xlim.offset)),
             axes = FALSE,type = "l", ylim = c(5,95), main = "stepwise", xlab = "")
        axis(1,
             at = seq(arg.training.set.endpoint - arg.xlim.offset,
                      arg.training.set.endpoint + arg.forecast.period, 5),
             labels = FALSE)

        text(seq(arg.training.set.endpoint - arg.xlim.offset,
                 arg.training.set.endpoint + arg.forecast.period, 5),
             par("usr")[3] - 10,
             labels = original.data[seq(arg.training.set.endpoint - arg.xlim.offset,
                                        arg.training.set.endpoint + arg.forecast.period, 5), 1],
             srt = 45,
             pos = 1,
             xpd = TRUE)


        axis(2, at = seq(5,95, 10), labels = TRUE, las = 1)

        abline(v = seq(arg.training.set.endpoint - arg.xlim.offset,
                       arg.training.set.endpoint + arg.forecast.period, 5),
               col = "springgreen4",
               lty = "dashed",
               lwd = par("lwd"))

        abline(h = seq(5,95, 10),
               col = "springgreen4",
               lty = "dashed",
               lwd = par("lwd"))

        lines(ts(estimated.kdj.d.stepwise, start = arg.training.set.endpoint + 1), type = "o", col = "purple")
        lines(ts(c(arg.kdj.k[(arg.training.set.endpoint - arg.xlim.offset) : (arg.training.set.endpoint)],
                  estimated.kdj.k.stepwise), start = (arg.training.set.endpoint - arg.xlim.offset)), col = "orange")
        lines(ts(estimated.kdj.k.stepwise, start = arg.training.set.endpoint + 1), type = "l", col = "blue")
        
        box()
        
        ###########
        
        # 
        if(arg.maxorder.flag == FALSE){
                return(fit.arima.kdj.d.stepwise)
        }

        print(system.time(fit.arima.kdj.d.stepwise.maxorder <- auto.arima(training.set.kdj.d,
                                                        max.order = 9,
                                                        stepwise = FALSE,
                                                        approximation = FALSE,
                                                        parallel = TRUE,
                                                        num.cores = 3)))

        estimated.kdj.d.stepwise.maxorder <- forecast(fit.arima.kdj.d.stepwise.maxorder, h = length(test.set.kdj.d))$mean

        plot(ts(c(arg.kdj.d[(arg.training.set.endpoint - arg.xlim.offset) : (arg.training.set.endpoint)],
                  estimated.kdj.d.stepwise.maxorder), start = (arg.training.set.endpoint - arg.xlim.offset)),
             axes = FALSE,type = "l", ylim = c(5,95), main = "stepwise")
        

        axis(1,
             at = seq(arg.training.set.endpoint - arg.xlim.offset,
                      arg.training.set.endpoint + arg.forecast.period, 5),
             labels = TRUE)

        axis(2, at = seq(5,95, 10), labels = TRUE, las = 1)

        abline(v = seq(arg.training.set.endpoint - arg.xlim.offset,
                       arg.training.set.endpoint + arg.forecast.period, 5),
               col = "springgreen4",
               lty = "dashed",
               lwd = par("lwd"))

        abline(h = seq(5,95, 10),
               col = "springgreen4",
               lty = "dashed",
               lwd = par("lwd"))

        lines(ts(estimated.kdj.d.stepwise.maxorder, start = arg.training.set.endpoint + 1), type = "o", col = "red")
        box()

        return(fit.arima.kdj.d.stepwise.maxorder)
}


```


```{r, fig.height=9, fig.width=10}
DrawKDJDForecastPlot(close.price, kdj.k, kdj.d, arg.forecast.period = 5, 
                 arg.ylabel.offset = 80,
                 arg.xlim.offset = 80,
                 arg.maxorder.flag = FALSE,
                 arg.training.set.endpoint = 300,
                 arg.start = 1)

```
        
```{r, fig.height=9, fig.width=10}
stopCluster(cluster)

```
